# Generated by Django 4.1.1 on 2022-09-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerList',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ServerName', models.CharField(max_length=100)),
                ('HostName', models.CharField(max_length=100)),
                ('IPAddress', models.CharField(max_length=100)),
                ('ServerToken', models.CharField(max_length=255)),
            ],
        ),
    ]
