# Generated by Django 4.1.1 on 2022-09-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ServerID', models.BigIntegerField(null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('CPUUsage', models.FloatField()),
                ('MemoryUsage', models.FloatField()),
                ('DiskUsage', models.FloatField()),
                ('UpTime', models.CharField(max_length=20)),
                ('Health', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='serverlist',
            name='ServerID',
            field=models.BigIntegerField(null=True),
        ),
    ]
