# Generated by Django 4.1.1 on 2022-09-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0002_serverstatus_serverlist_serverid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerID', models.BigIntegerField(null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('StartActivity', models.TimeField()),
                ('EndActivity', models.TimeField()),
                ('Activity', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
