# Generated by Django 4.1.1 on 2022-09-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0003_serveractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveractivity',
            name='Activity',
            field=models.CharField(max_length=400),
        ),
    ]
