# Generated by Django 4.1.1 on 2022-09-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0004_alter_serveractivity_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveractivity',
            name='Hostname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
