# Generated by Django 4.1.1 on 2022-09-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0005_serveractivity_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverstatus',
            name='ServerToken',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
