# Generated by Django 4.1.1 on 2022-09-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0006_serverstatus_servertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='Health',
            field=models.CharField(max_length=10),
        ),
    ]
