# Generated by Django 4.1.1 on 2022-09-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0007_alter_serverstatus_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='UpTime',
            field=models.CharField(max_length=30),
        ),
    ]
